INSERT INTO exercicio (nome, descricao) VALUES
('Supino Reto', 'Exercício para peitoral com barra no banco reto'),
('Supino Inclinado', 'Exercício para porção superior do peitoral'),
('Agachamento Livre', 'Exercício fundamental para pernas e glúteos'),
('Leg Press 45°', 'Exercício para quadríceps na máquina'),
('Remada Curvada', 'Exercício para dorsais com barra'),
('Puxada Alta', 'Exercício para dorsais na polia'),
('Desenvolvimento Militar', 'Exercício para ombros com barra'),
('Elevação Lateral', 'Exercício para deltóides laterais'),
('Rosca Direta', 'Exercício para bíceps com barra'),
('Rosca Scott', 'Exercício para bíceps no banco Scott'),
('Tríceps Testa', 'Exercício para tríceps com barra'),
('Tríceps Corda', 'Exercício para tríceps na polia com corda'),
('Elevação de Panturrilhas', 'Exercício para gastrocnêmio'),
('Abdominal Supra', 'Exercício para reto abdominal'),
('Prancha Abdominal', 'Exercício isométrico para core'),
('Burpee', 'Exercício completo de condicionamento'),
('Box Jump', 'Exercício pliométrico para potência'),
('Kettlebell Swing', 'Exercício balístico para cadeia posterior'),
('Flexão de Braço', 'Exercício de calistenia para peitoral'),
('Barra Fixa', 'Exercício para dorsais e braços');